name: Python Package

on:
    push:
      branches: [ main ]

jobs:
    deploy:
       runs-on: ubuntu-latest
       strategy:
         fail-fast: false
         matrix:
            python-version: [3.9]
       steps:
        - uses: actions/checkout@master
        - name: Initialize Python 3.7
          uses: actions/setup-python@v1
          with:
            python-version: ${{matrix.python-version}}
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt 

        - name: Run Bandit for static code analysis
          run: |
            pip install bandit
            bandit -r . -ll -ii -x **/tests/** 

        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/python@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            command: test
        
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: k3n3chukwu/cloud-monitor-gads:latest

        - name: Install Trivy
          run: |
            wget https://github.com/aquasecurity/trivy/releases/download/v0.20.0/trivy_0.20.0_Linux-64bit.tar.gz
            tar zxvf trivy_0.20.0_Linux-64bit.tar.gz
            sudo mv ./trivy /usr/local/bin/
            sudo chmod +x /usr/local/bin/trivy

        - name: Scan Docker image with Trivy for vulnerabilities
          run: trivy image k3n3chukwu/cloud-monitor-gads:latest

        - name: Run OWASP ZAP for security testing
          run: |
            sudo apt-get install -y openjdk-11-jre-headless
            wget -q -O - https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0_Linux.tar.gz | tar -xzf -
            sudo ./ZAP_2.10.0/zap.sh -daemon -port 8090 -config api.disablekey=true -host 0.0.0.0
        
        - name: CIS Benchmark Compliance Check
          run: |
            python cis_benchmark_checks.py
